### ISSUE TITLE
pecharts doesn't work in voila

### ISSUE THREAD

**Issue by dfguerrerom** [trungleduc/ipecharts#5]
I'm testing this package in `voila` and I get the following error:

```javascript
[Open Browser Console for more detailed log - Double click to close this message]
Failed to load model class 'EChartsWidgetModel' from module 'ipecharts'
Error: No version of module ipecharts is registered
    at T.loadClass (http://localhost:8888/voila/static/2336.voila.js:1:76307)
    at T.loadModelClass (http://localhost:8888/voila/static/2336.voila.js:1:73257)
    at T._make_model (http://localhost:8888/voila/static/2336.voila.js:1:70045)
    at T.new_model (http://localhost:8888/voila/static/2336.voila.js:1:67634)
    at http://localhost:8888/voila/static/2336.voila.js:1:68913
    at Array.map ()
    at T._loadFromKernel (http://localhost:8888/voila/static/2336.voila.js:1:68806)
    at async T.restoreWidgets (http://localhost:8888/voila/static/2336.voila.js:1:77796)
```

I have tested with `voila==0.5.7` and `voila<4` but the error is the same.

I also have the package files in my `jupyter/` folder:

```bash
:~/.local/share/jupyter/labextensions/ipecharts$ ls

install.json  package.json  static

```

Any idea what can be happening?

**Comment by trungleduc** [comment]
Thanks for reporting. I can reproduce the bug, will fix it soon

**Comment by trungleduc** [comment]
Fixed in 1.0.6

**Comment by dfguerrerom** [comment]
thanks!

**Comment by dfguerrerom** [comment]
@trungleduc, any chance to make it work with `voila<0.5` ?

**Comment by trungleduc** [comment]
it does not? I think I should.
